[MOBIA-3] 회원가입, 로그인 레이아웃
mobi-production/mobia-fe pull request #3
Opened 2024-10-10 12:35 UTC by yesoryeseul

## TL; DR
회원가입, 로그인 레이아웃을 작업하였습니다.

## CHANGES ?
1. login 네이밍을 sign-in으로 변경하여 sign-up과 통일하였습니다.(/auth/sign-in, auth/sign-up)
2. rhf + zod 추가하여 폼 유효성 검사 처리만 해두었습니다.
3. theme.ts 컬러 객체에 red_n(1~7) 속성들을 추가하였습니다. (컬러 확인은 피그마 - 컬러칩에 추가해두었습니다.)

2024-10-11 22:29 UTC, mobiorganization requested changes

2024-10-11 22:29 UTC, mobiorganization commented on src/apps/router/router.tsx
> +    ['sign-up']: signUpRoute
## RequestLevel
**의견이 필요해요**

## Description
sign-up page는 auth route에 속해있는 것이 아닌가요? sign-up route를 분리해서 따로 생성한 이유가 궁금해요 :)

2024-10-11 22:29 UTC, mobiorganization commented on src/domains/auth/components/signin-signup/auth-form-container.tsx
> +        direction='column'>
## RequestLevel
지나가는 의견이에요

## Description
Charka UI의 Center Component를 사용해보는 것은 어떨까요
[@see](https://v2.chakra-ui.com/docs/components/center%E3%85%81)

2024-10-11 22:29 UTC, mobiorganization commented on src/domains/auth/components/signin-signup/auth-input-field.tsx
> +}) => {
## RequestLevel
의견이 필요해요

## Description
해당 컴포넌트는 Auth라는 도메인에 종속된 InputFiled가 맞나요? 현재 주어진 기능으로 봤을 때는 Auth라는 도메인과 전혀 상관 없이 Button + TextFiled의 성격을 가지고 있는 것 같아요. 혹 Auth라는 도메인이 아닌 Core에서 관리해보는 것은 어떨까요

2024-10-11 22:29 UTC, mobiorganization commented on src/domains/auth/components/signin-signup/auth-submit-button.tsx
> +}) => {
## RequestLevel
**의견이 필요해요**

## Description
마찬가지에요 해당 Button은 현재 외부에서 isLoading 상태를 주입받는 것으로 보아 클릭 이벤트를 외부에서 주입 받아서 사용할 것으로 보이는데, 그렇다면 해당 버튼에는 Auth와 관련된 비즈니스 로직이 포함되어있지 않습니다.

설령, 비즈니스 로직을 Auth에 포함시킨다고 하더라도 domain 내에서도 컴포넌트를 features에 따라 분류하는 작업이 필요할 수도 있어요..! 위 구조는 좋은 의견이지만 하나의 구조로 가져갈지는 따로 논의를 해봐야 할 것 같아요.

2024-10-11 22:29 UTC, mobiorganization commented on src/domains/auth/constants/validate/schema.ts
> +})
## RequestLevel
**지나가는 의견이에요**

## Description
schema는 constants로 보기 어려울 것 같아요 :D 따로 schema 폴더로 빼는 것은 어떨까요 :)

2024-10-11 22:29 UTC, mobiorganization commented on src/domains/auth/components/signin-signup/auth-input-field.tsx
> +}
## RequestLevel
**의견이 필요해요**

## Description
다른 컴포넌트에서는 Props라 작성하고 위 컴포넌트에서 AuthInputFiledProps라고 명칭을 명확하게 해준 사유가 궁금해요 :) 또한 작성된 type 외 input의 다른 Props를 전달해야한다면 해당 컴포넌트에서는 type을 계속 추가해주어야하는걸까요!?

2024-10-11 22:29 UTC, mobiorganization commented on src/pages/auth/sign-up/page.tsx
> +        />
## RequestLevel
**수정이 필요해요**

## Description
React-Hook-Form을 사용하는한 sign-up의 Submit은 button이 아닌 form에 종속될 수 밖에 없어요 :) AuthSubmit이라는 도메인에 종속되지 않아있음에도 도메인명이 포함된 컴포넌트를 만드는 것이 좋은 관리 포인트를 제공하지는 않을 것 같습니다.

```suggestion
<Button variant='primary'>회원가입</Button>
```

2024-10-13 08:26 UTC, yesoryeseul commented on src/apps/router/router.tsx
>      }
Navigate 를 평소 잘 사용하지 않다보니 path, element 를 쓰는 다른 방법이라고 이해했습니다. 아래 방식으로 수정해두겠습니다!
`{
      path: '/sign-up',
      element: <SignUpPage />
    }`

2024-10-13 08:30 UTC, yesoryeseul commented on src/apps/router/router.tsx
> +    ['sign-up']: signUpRoute
모비아 [화면 목록](https://www.notion.so/fd8cf5327dc44383bd84d904d329e460) 에서 로그인과 회원가입이 1depth로 되어있어 해당 방식으로 설정을 했는데요.

1. route가 1depth 인 경우 같은 Route를 사용하는 방법이 있을까요?
2. 아니라면 로그인은 auth/sign-in 회원 가입은 auth/sign-up 이런 방식으로 라우팅 하면 될까요?

2024-10-13 08:40 UTC, yesoryeseul commented on src/domains/auth/components/signin-signup/auth-input-field.tsx
> +}
첫 번째 질문에 대한 대답은컴포넌트에서 Props 타입이 1개일 때 Props 로 설정하기로 했는데 초반에 작업했던 것이라 수정을 못헀네요.! Props 로 수정하겠습니다.
두 번째 질문에 대한 대답은 해당 부분은 고려하지 못했네요! `& InputHTMLAttributes<HTMLInputElement>` 을 추가하겠습니다.

2024-10-13 08:51 UTC, yesoryeseul commented on src/domains/auth/components/signin-signup/auth-input-field.tsx
> +}) => {
로그인, 회원가입 input 을 작업하면서 현재는 저 두곳 외에 다른 곳에서 사용되는 곳이 없다고 생각하여 domains로 빼 작성했었습니다. 범위를 좁게 보고 생각했던 것 같네요. core에서 관리하도록 하겠습니다!

2024-10-13 08:54 UTC, yesoryeseul commented on src/domains/auth/components/signin-signup/auth-submit-button.tsx
> +}) => {
이해했습니다! domains 를 조금 잘못 이해하고 있던 것 같네요. 해당 컴포넌트도 core에서 관리해보도록 하겠습니다!

2024-10-13 09:04 UTC, yesoryeseul commented on src/pages/auth/sign-up/page.tsx
> +        />
그렇군요. 이해했습니다. 재사용되는 컴포넌트 만드는 것에 중점이 계속 있었던 것 같습니다.

2024-10-25 12:52 UTC, mobiorganization approved these changes

2024-10-25 13:35 UTC, merged